services:
  ad-meet-calend:
    build:
      context: .
    container_name: ad-meet-calend-service
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html  
    develop:
      watch:
        - path: .
          target: /var/www/html
          action: sync
        - path: ./composer.json
          action: rebuild
        - path: ./composer.lock
          action: rebuild
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: ad-meet-calend-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootPassword
      MONGO_INITDB_DATABASE: calendardb
    ports:
      - "6666:27017"
    volumes:
      - ad-meet-calend-mongodb:/data/db/mongodb

  postgresql:
    image: postgres:15
    container_name: ad-meet-calend-postgresql
    restart: always
    environment:
      POSTGRES_USER: lutherdev
      POSTGRES_PASSWORD: calDBstr0ng
      POSTGRES_DB: calendardb
    ports:
      - "3333:5432"
    volumes:
      - ad-meet-calend-postgresql:/data/db/postgresql

volumes:
  ad-meet-calend-mongodb:
    driver: local
  ad-meet-calend-postgresql:
    driver: local
